/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.plotsky.spotikt

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = App("1", "2", "test", "test")
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
